Repository kubeflow/common, pull requests merged in 2019-05, with the labels that each got.

#25 Add skeleton code for reconcile service
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/service.go
  job_controller/test_job_controller.go
Labels: lgtm, size/L

#35 refine arguments of ControllerInterface.UpdateJobStatus
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/pod.go
  job_controller/test_job_controller.go
Labels: approved, lgtm, size/S

#36 Remove the podControl and serviceControl interfaces
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/pod.go
  job_controller/service.go
  job_controller/test_job_controller.go
Labels: approved, lgtm, size/L
