Repository kubeflow/common, pull requests merged in 2019-06, with the labels that each got.

#41 GetDefaultContainerPortNumber to GetDefaultContainerPortName
  job_controller/api/v1/interface.go
  job_controller/service.go
  job_controller/test_job_controller.go
  test_job/v1/test_job_controller.go
Labels: approved, lgtm, size/S

#42 Add readme
  README.md
Labels: approved, lgtm, size/M

#44 [hot-fix-43] change the job status api
  job_controller/api/v1/interface.go
  job_controller/job.go
  job_controller/test_job_controller.go
  test_job/v1/test_job_controller.go
Labels: approved, lgtm, size/XS
