Repository kubeflow/common, pull requests merged in 2019-04, with the labels that each got.

#6 Enable Travis CI on kubeflow/common
  .travis.yml
  go.sum
Labels: approved, lgtm, size/L

#9 Add Travis badge and Go report card
  README.md
Labels: approved, lgtm, size/XS

#12 Define interfaces for common job operators
  job_controller/job_controller.go
Labels: approved, lgtm, size/S

#13 Added schedulingPolicy api.
  operator/v1/types.go
Labels: approved, lgtm, ok-to-test, size/S

#15 Added missing generated lines in go.sum
  go.sum
Labels: approved, lgtm, size/S

#14 Add more utility functions for job and status
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/job_test.go
  job_controller/status.go
  job_controller/status_test.go
  job_controller/test_job_controller.go
  util/k8sutil/k8sutil.go
Labels: approved, lgtm, ok-to-test, size/XL

#16 Added .gitignore file
  .gitignore
Labels: approved, lgtm, size/M

#18 Update go.sum changed by golangci-lint
  go.sum
Labels: approved, lgtm, size/XS

#20 Fix incorrect name for restart policy exit code
  operator/v1/types.go
Labels: approved, lgtm, size/XS

#21 Remove mentions of tensorflow in test job
  test_job/v1/defaults.go
Labels: approved, lgtm, size/XS

#17 Add utility methods for pod creation
  .travis.yml
  job_controller/job_controller.go
  job_controller/pod.go
  job_controller/pod_test.go
  job_controller/test_job_controller.go
Labels: approved, lgtm, size/L

#27 chore: Fix package name
  test_util/v1/const.go
  test_util/v1/pod.go
  test_util/v1/service.go
  test_util/v1/test_job_util.go
  test_util/v1/util.go
Labels: approved, lgtm, size/S

#26 test: Add util/train/train_util_test.go
  util/train/train_util_test.go
Labels: approved, lgtm, size/M

#24 Add utility methods for job reconciliation
  .travis.yml
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/job_test.go
  job_controller/test_job_controller.go
Labels: approved, lgtm, size/L

#29 Unify the label keys
  job_controller/job_controller.go
  job_controller/pod.go
  job_controller/service.go
  job_controller/test_job_controller.go
Labels: approved, lgtm, size/M

#30 Make UpdateJobConditions public to be used by custom operators
  job_controller/job.go
  job_controller/job_controller.go
  job_controller/pod.go
  job_controller/service.go
  job_controller/status.go
  job_controller/status_test.go
  job_controller/test_job_controller.go
  util/status.go
  util/status_test.go
Labels: approved, lgtm, size/XL

#32 Correct function names in the comment
  job_controller/job_controller.go
Labels: approved, lgtm, size/S
