Repository kubeflow/common, pull requests merged in 2020-04, with the labels that each got.

#61 Add distributed training operator roadmap
  ROADMAP.md
Labels: approved, lgtm, size/M

#69 Add links to issues on ROADMAP.md
  ROADMAP.md
Labels: approved, lgtm, size/S

#62 Import volcano api
  go.mod
  go.sum
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/pod.go
Labels: approved, lgtm, size/L

#72 Move Pods/Services control interface to separate folder
  go.mod
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/control/pod_control.go
  pkg/controller.v1/control/pod_control_test.go
  pkg/controller.v1/control/service_control.go
  pkg/controller.v1/control/service_control_test.go
  pkg/controller.v1/control/service_ref_manager.go
  pkg/controller.v1/control/service_ref_manager_test.go
  pkg/controller.v1/control/utils.go
Labels: approved, lgtm, size/L

#76 Update comments on the use of -ignore flag for goveralls
  .travis.yml
Labels: approved, lgtm, size/S

#75 Add Prometheus metrics for service creation
  go.mod
  go.sum
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/service.go
Labels: approved, lgtm, size/M

#73 Add PodControlInterface and PodControllerRefManager
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/control/controller_ref_manager.go
  pkg/controller.v1/control/controller_ref_manager_test.go
  pkg/controller.v1/control/pod_control.go
  pkg/controller.v1/control/service_control.go
  pkg/controller.v1/control/service_ref_manager.go
Labels: approved, lgtm, size/XL

#74 Create expectation package
  .travis.yml
  go.mod
  linter_config.yaml
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/util.go
  pkg/controller.v1/expectation/expectation.go
  pkg/controller.v1/expectation/expectation_test.go
  pkg/controller.v1/expectation/util.go
Labels: approved, lgtm, size/L

#78 Add DEVELOPMENT.md doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/M
