Repository kubeflow/common, pull requests merged in 2020-05, with the labels that each got.

#77 Add proposal for Prometheus metrics coverage
  docs/prometheus-metrics.md
Labels: approved, lgtm, size/M

#79 Edits on dev guide and rename it to CONTRIBUTING.md
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/L

#80 Add @Jeffwan to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#81 Fix crash when ReplicaSpec.Replicas is nil
  go.mod
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/XS

#82 Add Prometheus metrics for pod created/deleted/failed
  pkg/controller.v1/common/pod.go
Labels: approved, lgtm, size/S

#83 Reformat code with go fmt and check this on Travis CI
  .travis.yml
  go.mod
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/service_test.go
  pkg/controller.v1/control/controller_ref_manager_test.go
  pkg/controller.v1/control/pod_control.go
  pkg/controller.v1/control/service_control.go
Labels: approved, lgtm, size/M

#84 Add scheduling related Prometheus metrics
  pkg/controller.v1/common/job_controller.go
Labels: approved, lgtm, size/M

#85 Simplify interfaces and remove useless interfaces
  pkg/apis/common/v1/interface.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/job_test.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: approved, lgtm, size/L

#88 Add release notes document
  RELEASE.md
Labels: approved, lgtm, size/M

#87 Bump Kubernetes dependency to 1.16.9
  go.mod
  go.sum
  pkg/apis/common/v1/openapi_generated.go
  pkg/controller.v1/expectation/expectation_test.go
  pkg/util/k8sutil/client.go
  test_job/apis/test_job/v1/openapi_generated.go
  test_job/client/clientset/versioned/clientset.go
  test_job/client/informers/externalversions/test_job/interface.go
Labels: approved, lgtm, size/XXL

#90 Change expectation package log level to debug
  pkg/controller.v1/expectation/expectation.go
Labels: approved, lgtm, size/S

#91 Provides more flexibility for customizations
  pkg/apis/common/v1/interface.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/job_test.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: approved, lgtm, size/M

#93 Skip some logics for terminated job and add PodGroup reconcile loop
  pkg/controller.v1/common/job.go
Labels: approved, lgtm, size/L

#95 Add v0.3.1 release notes
  RELEASE.md
Labels: approved, lgtm, size/XS
