Repository kubeflow/common, pull requests merged in 2021-08, with the labels that each got.

#150 Add fully-qualified labels
  pkg/apis/common/v1/constants.go
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/pod_test.go
  pkg/controller.v1/common/service.go
  pkg/util/labels/labels.go
  pkg/util/labels/labels_test.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: approved, lgtm, size/L

#152 Fix ReplicaType key for filtering pods and services
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/pod_test.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/service_test.go
Labels: approved, lgtm, size/M

#141 feat(common) add reconciler.v1
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/pod_test.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/service_test.go
  pkg/controller.v1/common/status.go
  pkg/controller.v1/common/util.go
  pkg/core/job.go
  pkg/core/pod.go
  pkg/core/service.go
  pkg/core/status.go
  pkg/core/utils.go
  pkg/reconciler.v1/common/README.md
  pkg/reconciler.v1/common/gang.go
  pkg/reconciler.v1/common/gang_scheduler_framework.go
  pkg/reconciler.v1/common/gang_volcano.go
  pkg/reconciler.v1/common/interface.go
  pkg/reconciler.v1/common/job.go
  pkg/reconciler.v1/common/pod.go
  pkg/reconciler.v1/common/pod_test.go
  pkg/reconciler.v1/common/reconciler.go
  pkg/reconciler.v1/common/service.go
  pkg/reconciler.v1/common/service_test.go
  pkg/reconciler.v1/common/utils.go
  pkg/reconciler.v1/common/utils_test.go
  pkg/util/counter.go
  test_job/reconciler.v1/test_job/dummy_client.go
  test_job/reconciler.v1/test_job/test_job_reconciler.go
Labels: approved, lgtm, size/XXL

#158 Revert #135: change rtype to commonv1.ReplicaType
  pkg/apis/common/v1/interface.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/util.go
  pkg/controller.v1/common/util_test.go
  pkg/controller.v1/expectation/util.go
  pkg/util/logger.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: approved, lgtm, size/M
