Repository kubeflow/common, pull requests merged in 2021-09, with the labels that each got.

#161 fix: add missing dependencies and missing methods
  go.mod
  go.sum
  pkg/reconciler.v1/common/job.go
Labels: approved, lgtm, size/L

#164 Move ci from travis to github actions
  .github/workflows/build.yml
  .travis.yml
  README.md
Labels: approved, lgtm, size/M

#165 Make goveralls step in ci optional
  .github/workflows/build.yml
Labels: approved, lgtm, size/XS
