Repository kubeflow/common, pull requests merged in 2021-11, with the labels that each got.

#172 Fix openapi generate rule violation
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/types.go
Labels: approved, lgtm, size/XS

#174 Rollback #172 as it introduce hard requirements for the list values to not be empty
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/types.go
Labels: approved, lgtm, size/XS

#173 Revert ReplicaType to string
  pkg/apis/common/v1/interface.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/util.go
  pkg/controller.v1/common/util_test.go
  pkg/controller.v1/expectation/util.go
  pkg/core/job.go
  pkg/core/pod.go
  pkg/core/service.go
  pkg/core/utils.go
  pkg/reconciler.v1/common/gang_volcano.go
  pkg/reconciler.v1/common/interface.go
  pkg/reconciler.v1/common/job.go
  pkg/reconciler.v1/common/pod.go
  pkg/reconciler.v1/common/pod_test.go
  pkg/reconciler.v1/common/service.go
  pkg/reconciler.v1/common/service_test.go
  pkg/util/labels/labels.go
  pkg/util/logger.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: approved, lgtm, size/L

#177 feat: Add LabelSelector
  .github/workflows/build.yml
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/types.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
  pkg/apis/common/v1/zz_generated.defaults.go
  test_job/apis/test_job/v1/openapi_generated.go
  test_job/apis/test_job/v1/zz_generated.deepcopy.go
  test_job/apis/test_job/v1/zz_generated.defaults.go
Labels: approved, lgtm, size/S

#178 feat(job): Add a check to avoid null pointer exception
  pkg/controller.v1/common/job.go
Labels: approved, lgtm, size/XS

#180 delete podgroup before clean job
  pkg/controller.v1/common/job.go
Labels: approved, lgtm, size/XS
