Repository kubeflow/common, pull requests merged in 2021-02, with the labels that each got.

#111 feat: Remove k8s.io/kubernetes from go mod
  go.mod
  go.sum
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/control/pod_control_test.go
  pkg/controller.v1/control/service_control_test.go
  pkg/controller.v1/expectation/expectation_test.go
Labels: approved, size/M

#114 feat: Add docs for API
  README.md
  docs/api/autogen/config.yaml
  docs/api/autogen/templates/gv_details.tpl
  docs/api/autogen/templates/gv_list.tpl
  docs/api/autogen/templates/type.tpl
  docs/api/autogen/templates/type_members.tpl
  docs/api/generated.asciidoc
  hack/generate-apidoc.sh
Labels: approved, lgtm, size/L

#115 Add tfjob annotations to podgroup.
  pkg/controller.v1/common/job_controller.go
Labels: approved, lgtm, size/XS
