Repository kubeflow/common, pull requests merged in 2022-06, with the labels that each got.

#194 Update all k8s dependencies to 0.24.1
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
  pkg/apis/common/v1/zz_generated.defaults.go
  pkg/controller.v1/expectation/expectation.go
  pkg/controller.v1/expectation/expectation_test.go
  test_job/apis/test_job/v1/openapi_generated.go
  test_job/apis/test_job/v1/zz_generated.deepcopy.go
  test_job/apis/test_job/v1/zz_generated.defaults.go
  test_job/client/clientset/versioned/clientset.go
  test_job/client/clientset/versioned/doc.go
  test_job/client/clientset/versioned/fake/clientset_generated.go
  test_job/client/clientset/versioned/fake/doc.go
  test_job/client/clientset/versioned/fake/register.go
  test_job/client/clientset/versioned/scheme/doc.go
  test_job/client/clientset/versioned/scheme/register.go
  test_job/client/clientset/versioned/typed/test_job/v1/doc.go
  test_job/client/clientset/versioned/typed/test_job/v1/fake/doc.go
  test_job/client/clientset/versioned/typed/test_job/v1/fake/fake_test_job_client.go
  test_job/client/clientset/versioned/typed/test_job/v1/fake/fake_testjob.go
  test_job/client/clientset/versioned/typed/test_job/v1/generated_expansion.go
  test_job/client/clientset/versioned/typed/test_job/v1/test_job_client.go
  test_job/client/clientset/versioned/typed/test_job/v1/testjob.go
  test_job/client/informers/externalversions/factory.go
  test_job/client/informers/externalversions/generic.go
  test_job/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  test_job/client/informers/externalversions/test_job/interface.go
  test_job/client/informers/externalversions/test_job/v1/interface.go
  test_job/client/informers/externalversions/test_job/v1/testjob.go
  test_job/client/listers/test_job/v1/expansion_generated.go
  test_job/client/listers/test_job/v1/testjob.go
Labels: approved, lgtm, size/XXL

#189 Handle pod failures for all policies
  pkg/controller.v1/common/pod.go
Labels: approved, lgtm, size/S

#190 Fix exitCode check
  pkg/util/train/train_util.go
Labels: approved, lgtm, size/M
