Repository kubeflow/common, pull requests merged in 2023-01, with the labels that each got.

#206 Adding compatibility for API supporting HPA
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/types.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#201 add JobFailedValidation reason constant
  pkg/util/status.go
Labels: approved, lgtm, size/XS

#207 Support for PodGroup updates
  go.mod
  pkg/controller.v1/common/scheduling.go
  pkg/controller.v1/control/podgroup_control.go
Labels: approved, lgtm, size/M

#208 Upgrade PriorityClass apiVersion to scheduling.k8s.io/v1
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/service_test.go
  pkg/controller.v1/common/util.go
  pkg/reconciler.v1/common/gang_scheduler_framework.go
  pkg/reconciler.v1/common/gang_volcano.go
Labels: approved, lgtm, size/S
